src/sighandler.c: fix `sigtermSigHandler` proto (`gcc-15` fix)
`gcc-15` switched to `c23` by default
(https://gcc.gnu.org/gcc-15/porting_to.html) which made `void f()` into
`void f(void)`. This exposed build failure against it as:

```
sighandler.c: In function 'setSigHandler':
sighandler.c:68:18: error: passing argument 2 of 'signal' from incompatible pointer type [-Wincompatible-pointer-types]
   68 |  signal(SIGTERM, sigtermSigHandler);
      |                  ^~~~~~~~~~~~~~~~~
```